# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=255)),
            ],
        ),
    ]
